benchmarks:
- libarchive_libarchive_fuzzer
- zstd_stream_decompress
concurrent_builds: 2
custom_seed_corpus_dir: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: seamfastertest40
experiment_filestore: /home/frango/8tb/frango/icse_data
fuzzers:
- newseamnomem
- newseam
- aflpp
- newseamfast
git_hash: f1c12914a4ca74073131c5744dfc6b33c33579be
local_experiment: true
max_total_time: 86400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
region_coverage: false
report_filestore: /home/frango/8tb/frango/icse_report
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
snapshot_period: 900
trials: 3
